### PR TITLE
Feature/update metaflow

### PR DESCRIPTION
**Pull request by pikulmar**

### CODE REVIEW

**Comment by pikulmar** [comment]
@fortum-vaanavil Since Metaflow does not use `black`, I resolved conflicts preferentially keeping the Metaflow code.

**Review by benbemoh — APPROVED** [review]
LGTM

**Comment by pikulmar** [comment]
Still testing this, takes a while...

**Comment by pikulmar** [comment]
* Local execution of `e2e-reference-model` works
* Local execution of `e2e-reference-model` with AWS Batch works
* EKS-based execution of `e2e-reference-model` works
* EKS-based execution of `e2e-reference-model` with AWS Batch works

Could be nice to have those tests done by CI...

**Pull request merged**
